#!/Users/eric/Documents/virtualenvs/pygments-lasso/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'Pygments==1.5dev-20120915','console_scripts','pygmentize'
__requires__ = 'Pygments==1.5dev-20120915'
import sys
from pkg_resources import load_entry_point

sys.exit(
   load_entry_point('Pygments==1.5dev-20120915', 'console_scripts', 'pygmentize')()
)
