/* SF bug #3826: "limit returns temp variable expression" */

(kill (q, a, x),
 ctxt: newcontext (),
 assume (q > 0),
 limit(x^q/(a*x^q- 1),x,inf));
'limit(1/(a- 1/x^q),x,inf);

tlimit(x^q/(a*x^q- 1),x,inf);
'limit(1/(a- 1/x^q),x,inf);

(assume (a > 0),
 declare (q, integer),
 limit(x^q/(a*x^q- 1),x,inf));
1/a;

(remove (q, integer),
 declare (q, noninteger),
 limit(x^q/(a*x^q- 1),x,inf));
1/a;

(remove (q, noninteger),
 killcontext (ctxt));
done;
