/* ---------------------------------
This is an example file containing qlik script
--------------------------------- */

LET vFilePath = '/home';

FOR EACH vFolder IN 'folder_1', 'folder_2'

    // Check the file exists
    IF FILESIZE('$(vFilePath)/$(vFolder)/file.qvd') >0 THEN

        TABLE_NAME:
        NoConcatenate
        LOAD
            [Field 1]   AS FIELD_1,
            "Field 2"   AS FIELD_2,
            FIELD_3,
            FileName()      AS SOURCE_FILE
        FROM
            [$(vFilePath)/$(vFolder)/file.qvd] (qvd);

        MAP_FIELD_1:
        MAPPING LOAD
            FIELD_1,
            SUM(FIELD_2)
        RESIDENT
            TABLE_NAME
        GROUP BY
            FIELD_1;

        LEFT JOIN(TABLE_NAME)
        LOAD DISTINCT
            FIELD_1,
            FIELD_2,
            FIELD_3,
            applymap('MAP_FIELD_1', FIELD_1, 0)     AS FIELD_2_SUM,
            'Token String'                          AS STRING_FIELD,
            3.14159                                 AS NUMBER_FIELD
        RESIDENT
            TABLE_NAME
        ORDER BY
            FIELD_3 DESC;

        STORE TABLE_NAME INTO [$(vFilePath)/$(vFolder)/file_output.qvd] (qvd);

        DROP TABLE TABLE_NAME;

    ELSE

        TRACE No file found in $(vFilePath)/file.qvd;

    END IF

NEXT vFolder