"""
    pygments.lexers.netlogo
    ~~~~~~~~~~~~~~~~~~~~~~~

    Lexers for the NetLogo programming language.

    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS.
    :license: BSD, see LICENSE for details.
"""

from pygments.lexer import RegexLexer, words
from pygments.token import Comment, Keyword, Name, Number, Operator, \
        Punctuation, String, Whitespace

__all__ = ['NetLogoLexer']

class NetLogoLexer(RegexLexer):
    """
    A lexer for NetLogo.
    """

    name = 'NetLogo'
    aliases = ['netlogo']
    url = 'https://netlogo.org/'
    version_added = '2.20'

    # nlogo and nlogox files contain things other than NetLogo code, so this
    # lexer wouldn't work with them.
    filenames = ['*.nls']

    # Lists of commands, keywords, reporters, operators, and constants below
    # are based on https://github.com/NetLogo/highlight-nl, which is in public
    # domain.
    commands = [
        '__bench',
        '__change-topology',
        '__done',
        '__experimentstepend',
        '__export-drawing',
        '__foreverbuttonend',
        '__ignore',
        '__let',
        '__linkcode',
        '__make-preview',
        '__mkdir',
        '__observercode',
        '__patchcode',
        '__plot-pen-hide',
        '__plot-pen-show',
        '__pwd',
        '__reload-extensions',
        '__set-line-thickness',
        '__stderr',
        '__stdout',
        '__thunk-did-finish',
        '__turtlecode',
        'ask',
        'ask-concurrent',
        'auto-plot-off',
        'auto-plot-on',
        'back',
        'beep',
        'bk',
        'ca',
        'carefully',
        'cd',
        'clear-all',
        'clear-all-plots',
        'clear-drawing',
        'clear-globals',
        'clear-links',
        'clear-output',
        'clear-patches',
        'clear-plot',
        'clear-ticks',
        'clear-turtles',
        'cp',
        'create-link-from',
        'create-link-to',
        'create-link-with',
        'create-links-from',
        'create-links-to',
        'create-links-with',
        'create-ordered-turtles',
        'create-temporary-plot-pen',
        'create-turtles',
        'cro',
        'crt',
        'ct',
        'die',
        'diffuse',
        'diffuse4',
        'display',
        'downhill',
        'downhill4',
        'error',
        'every',
        'export-all-plots',
        'export-interface',
        'export-output',
        'export-plot',
        'export-view',
        'export-world',
        'face',
        'facexy',
        'fd',
        'file-close',
        'file-close-all',
        'file-delete',
        'file-flush',
        'file-open',
        'file-print',
        'file-show',
        'file-type',
        'file-write',
        'follow',
        'follow-me',
        'foreach',
        'forward',
        'hatch',
        'hide-link',
        'hide-turtle',
        'histogram',
        'home',
        'ht',
        'if',
        'if-else',
        'ifelse',
        'import-drawing',
        'import-pcolors',
        'import-pcolors-rgb',
        'import-world',
        'inspect',
        'jump',
        'layout-circle',
        'layout-radial',
        'layout-spring',
        'layout-tutte',
        'left',
        'let',
        'loop',
        'lt',
        'move-to',
        'no-display',
        'output-print',
        'output-show',
        'output-type',
        'output-write',
        'pd',
        'pe',
        'pen-down',
        'pen-erase',
        'pen-up',
        'pendown',
        'penup',
        'plot',
        'plot-pen-down',
        'plot-pen-reset',
        'plot-pen-up',
        'plotxy',
        'print',
        'pu',
        'random-seed',
        'repeat',
        'report',
        'reset-perspective',
        'reset-ticks',
        'reset-timer',
        'resize-world',
        'ride',
        'ride-me',
        'right',
        'rp',
        'rt',
        'run',
        'set',
        'set-current-directory',
        'set-current-plot',
        'set-current-plot-pen',
        'set-default-shape',
        'set-histogram-num-bars',
        'set-patch-size',
        'set-plot-pen-color',
        'set-plot-pen-interval',
        'set-plot-pen-mode',
        'set-plot-x-range',
        'set-plot-y-range',
        'setup-plots',
        'setxy',
        'show',
        'show-link',
        'show-turtle',
        'sprout',
        'st',
        'stamp',
        'stamp-erase',
        'stop',
        'tick',
        'tick-advance',
        'tie',
        'type',
        'untie',
        'update-plots',
        'uphill',
        'uphill4',
        'user-message',
        'wait',
        'watch',
        'watch-me',
        'while',
        'with-local-randomness',
        'without-interruption',
        'write'
    ]

    keywords = [
        'breed',
        'to',
        'to-report',
        'end',
        'globals',
        'turtles-own',
        'links-own',
        'patches-own',
        'directed-link-breed',
        'undirected-link-breed',
        'extensions',
        '__includes'
    ]

    operators = [
        '!=',
        '*',
        '+',
        '-',
        '/',
        '<',
        '<=',
        '=',
        '>',
        '>=',
        '^'
    ]

    reporters = [
        '__boom',
        '__check-syntax',
        '__dump',
        '__dump-extension-prims',
        '__dump-extensions',
        '__dump1',
        '__hubnet-in-q-size',
        '__hubnet-out-q-size',
        '__nano-time',
        '__patchcol',
        '__patchrow',
        '__processors',
        '__random-state',
        '__stack-trace',
        '__to-string',
        'abs',
        'acos',
        'all?',
        'and',
        'any?',
        'approximate-hsb',
        'approximate-rgb',
        'asin',
        'at-points',
        'atan',
        'autoplot?',
        'base-colors',
        'behaviorspace-run-number',
        'bf',
        'bl',
        'both-ends',
        'but-first',
        'but-last',
        'butfirst',
        'butlast',
        'can-move?',
        'ceiling',
        'cos',
        'count',
        'date-and-time',
        'distance',
        'distance-nowrap',
        'distancexy',
        'distancexy-nowrap',
        'dx',
        'dy',
        'empty?',
        'end1',
        'end2',
        'error-message',
        'exp',
        'extract-hsb',
        'extract-rgb',
        'file-at-end?',
        'file-exists?',
        'file-read',
        'file-read-characters',
        'file-read-line',
        'filter',
        'first',
        'floor',
        'fput',
        'hsb',
        'hubnet-clients-list',
        'hubnet-enter-message?',
        'hubnet-exit-message?',
        'hubnet-message',
        'hubnet-message-source',
        'hubnet-message-tag',
        'hubnet-message-waiting?',
        'ifelse-value',
        'in-cone',
        'in-cone-nowrap',
        'in-link-from',
        'in-link-neighbor?',
        'in-link-neighbors',
        'in-radius',
        'in-radius-nowrap',
        'int',
        'is-agent?',
        'is-agentset?',
        'is-boolean?',
        'is-command-task?',
        'is-directed-link?',
        'is-link-set?',
        'is-link?',
        'is-list?',
        'is-number?',
        'is-patch-set?',
        'is-patch?',
        'is-reporter-task?',
        'is-string?',
        'is-turtle-set?',
        'is-turtle?',
        'is-undirected-link?',
        'item',
        'last',
        'length',
        'link',
        'link-heading',
        'link-length',
        'link-neighbor?',
        'link-neighbors',
        'link-set',
        'link-shapes',
        'link-with',
        'links',
        'list',
        'ln',
        'log',
        'lput',
        'map',
        'max',
        'max-n-of',
        'max-one-of',
        'max-pxcor',
        'max-pycor',
        'mean',
        'median',
        'member?',
        'min',
        'min-n-of',
        'min-one-of',
        'min-pxcor',
        'min-pycor',
        'mod',
        'modes',
        'mouse-down?',
        'mouse-inside?',
        'mouse-xcor',
        'mouse-ycor',
        'movie-status',
        'my-in-links',
        'my-links',
        'my-out-links',
        'myself',
        'n-of',
        'n-values',
        'neighbors',
        'neighbors4',
        'netlogo-applet?',
        'netlogo-version',
        'netlogo-web?',
        'new-seed',
        'no-links',
        'no-patches',
        'no-turtles',
        'not',
        'of',
        'one-of',
        'or',
        'other',
        'other-end',
        'out-link-neighbor?',
        'out-link-neighbors',
        'out-link-to',
        'patch',
        'patch-ahead',
        'patch-at',
        'patch-at-heading-and-distance',
        'patch-here',
        'patch-left-and-ahead',
        'patch-right-and-ahead',
        'patch-set',
        'patch-size',
        'patches',
        'plot-name',
        'plot-pen-exists?',
        'plot-x-max',
        'plot-x-min',
        'plot-y-max',
        'plot-y-min',
        'position',
        'precision',
        'random',
        'random-exponential',
        'random-float',
        'random-gamma',
        'random-normal',
        'random-or-random-float',
        'random-poisson',
        'random-pxcor',
        'random-pycor',
        'random-xcor',
        'random-ycor',
        'read-from-string',
        'reduce',
        'remainder',
        'remove',
        'remove-duplicates',
        'remove-item',
        'replace-item',
        'reverse',
        'rgb',
        'round',
        'run-result',
        'runresult',
        'scale-color',
        'se',
        'self',
        'sentence',
        'shade-of?',
        'shapes',
        'shuffle',
        'sin',
        'sort',
        'sort-by',
        'sort-on',
        'sqrt',
        'standard-deviation',
        'subject',
        'sublist',
        'substring',
        'subtract-headings',
        'sum',
        'tan',
        'task',
        'ticks',
        'timer',
        'towards',
        'towards-nowrap',
        'towardsxy',
        'towardsxy-nowrap',
        'turtle',
        'turtle-set',
        'turtles',
        'turtles-at',
        'turtles-here',
        'turtles-on',
        'user-directory',
        'user-file',
        'user-input',
        'user-new-file',
        'user-one-of',
        'user-yes-or-no?',
        'value-from',
        'values-from',
        'variance',
        'with',
        'with-max',
        'with-min',
        'word',
        'world-height',
        'world-width',
        'wrap-color',
        'xor',

        # turtle variables
        'who',
        'color',
        'heading',
        'xcor',
        'ycor',
        'shape',
        'label',
        'label-color',
        'breed',
        'hidden?',
        'size',
        'pen-size',
        'pen-mode',

        # patch variables
        'pxcor',
        'pycor',
        'pcolor',
        'plabel',
        'plabel-color',

        # link variables
        'end1',
        'end2',
        'color',
        'label',
        'label-color',
        'hidden?',
        'breed',
        'thickness',
        'shape',
        'tie-mode'
    ]

    constants = [
        'true',
        'false',
        'nobody',
        'e',
        'pi',
        'gray',
        'grey',
        'red',
        'orange',
        'brown',
        'yellow',
        'green',
        'lime',
        'turquoise',
        'cyan',
        'sky',
        'blue',
        'violet',
        'magenta',
        'pink',
        'black',
        'white'
    ]

    tokens = {
        'root': [
            (r';.*', Comment),
            (words(['[', ']']), Punctuation),
            (words(keywords, r'(?<=\s)', r'(?=\s)'), Keyword),
            (words(commands + reporters, r'(?<=\s)', r'(?=\s)'), Name.Builtin),
            (words(constants, r'(?<=\s)', r'(?=\s)'), Name.Variable),
            (words(operators, r'(?<=\s)', r'(?=\s)'), Operator),
            (r'(?:[0-9]+\.[0-9]*|[0-9]*.[0-9]+)e[0-9]+', Number), # scientific
            (r'[0-9]*\.[0-9]*', Number),
            (r'"(?:[^"\\]|\\.)*"', String),
            (r'[^\[\]\s]+', Name),
            (r'\s+', Whitespace)
        ]
    }
